### ISSUE TITLE
Cannot find module 'ts-morph

### ISSUE THREAD

**Issue by oaj** [mariusespejo/team-seas-clone#1]
Hi Marius
I followed your tutorial and came as far as `npm run gen-typings `, where it gave the Error: **Cannot find module 'ts-morph'**
Installing ts-morph didn't help - it still couldn't find it.
On the internet I saw that other people had the same problem and the reason is some changes in a new version, but I found no solution.
Do you have any idea how to solve it ?

[System Information]
OS Version     : Linux 5.15
NodeJS Version : v16.13.1
NPM Version    : 8.1.2 

[Nest CLI]
Nest CLI Version : 8.2.4 

[Nest Platform Information]
platform-express version : 8.4.2
mapped-types version     : 1.0.1
schematics version       : 8.0.8
testing version          : 8.4.2
common version           : 8.4.2
core version             : 8.4.2

Best regards Ole

**Comment by mariusespejo** [comment]
Hey there, the only solution is to actually install it. If it still can’t find it I’m not really sure what the problem is, try deleting node modules and reinstall everything. 

More details here: https://github.com/nestjs/graphql/issues/1621#issuecomment-878199238

Unfortunately the landscape of open source changes quickly, if you want to have the same exact result as the tutorial (which is now almost half a year old), you’ll have to install mostly the same dependencies. The repo includes a `package.json` and a `package-lock.json` which you can copy directly to achieve mostly the same install that I did in the tutorial. 

I’m sorry I can’t help more but hope that helps.
